//
//  CarClassifierViewModel.swift
//  RevEye
//
//  Created by user on 17/11/2025.
//


import Foundation
import Vision
import CoreML
import UIKit

class CarClassifierViewModel: ObservableObject {
    @Published var result: String = "No result yet"

    private var visionModel: VNCoreMLModel

    init() {
        // Load the Core ML model you added to your project
        do {
            // Replace `CarClassifier` with the actual autogenerated class name for your .mlmodel
            let coreMLModel = try CarClassifier(configuration: MLModelConfiguration())
            visionModel = try VNCoreMLModel(for: coreMLModel.model)
        } catch {
            fatalError("Could not load ML model: \(error)")
        }
    }

    func classify(image: UIImage) {
        guard let ciImage = CIImage(image: image) else {
            DispatchQueue.main.async {
                self.result = "Failed to convert UIImage to CIImage"
            }
            return
        }

        let request = VNCoreMLRequest(model: visionModel) { [weak self] request, error in
            if let observations = request.results as? [VNClassificationObservation],
               let top = observations.first {
                DispatchQueue.main.async {
                    // top.identifier is the predicted label
                    // top.confidence is how confident the model is (0–1)
                    self?.result = "\(top.identifier) — \(String(format: "%.1f%%", top.confidence * 100))"
                }
            } else {
                DispatchQueue.main.async {
                    self?.result = "No classification result"
                }
            }
        }

        let handler = VNImageRequestHandler(ciImage: ciImage, options: [:])
        DispatchQueue.global(qos: .userInitiated).async {
            do {
                try handler.perform([request])
            } catch {
                DispatchQueue.main.async {
                    self.result = "Failed image request: \(error.localizedDescription)"
                }
            }
        }
    }
}
